### PR TITLE
fix component instrumentation

### PR DESCRIPTION
**Pull request by anmonteiro**

### CODE REVIEW

**Comment by swannodette** [comment]
@anmonteiro is this PR still valid I'm trying to remember if there weren't other bigger issues here.

**Comment by anmonteiro** [comment]
@swannodette definitely valid, this was submitted so that you could evaluate if the `instrument?` flag in `factory` was a good design decision.

**Comment by swannodette** [comment]
@anmonteiro ah but an internal thing, this is to prevent the infinite recursion right?

**Comment by anmonteiro** [comment]
@swannodette that's exactly right

**Pull request merged**
