### PR TITLE
Fix Logging in set-query! (easy merge)

### PR DESCRIPTION
**Pull request by alexanderkiel**
Closes: #865

### CODE REVIEW

**Comment by anmonteiro** [comment]
It doesn't look like this PR is achieving anything new. Isn't the behavior equivalent?

**Comment by wilkerlucio** [comment]
@anmonteiro it's not the same, the old version was "swallowing" the first items from the `when`, this one concatenates and returns the full string.

From old code: `(when query "changed query '" query ", ")` -> would just return `", "`

**Comment by anmonteiro** [comment]
Gotcha, but why change the whole thing and not simply wrap those cases in `str`?

**Comment by wilkerlucio** [comment]
I believe was a matter of styling, but can't say much, it just seems to fix the issue.

**Comment by alexanderkiel** [comment]
I'll answer later. Have to fix another thing first.

**Comment by alexanderkiel** [comment]
@anmonteiro I replaced the `when`s with `cond->`. `cond->` is already used quite often in om. So I was comfortable to use it here. If you don't like it, I can change the pull request.

**Comment by swannodette** [comment]
@alexanderkiel have you submitted your Om Contributor Agreement? The change looks fine.

**Comment by alexanderkiel** [comment]
@swannodette I've send you a mail.

**Comment by alexanderkiel** [comment]
@swannodette Any news on this?

**Pull request merged**
