### PR TITLE
React 16 support

### PR DESCRIPTION
**Pull request by anmonteiro**
This supersedes #883

### CODE REVIEW

**Comment by anmonteiro** [comment]
I don't know if this is ready to be merged yet. 

I'm tracking down what seems like missing externs, as our app is misbehaving with advanced compilation.

**Comment by swannodette** [comment]
Ok ready for this when you are.

**Comment by anmonteiro** [comment]
There's still an issue here, which breaks this line:
https://github.com/omcljs/om/blob/bc1c30f8c2e17bfc0821da7283c7aa2253ad0e89/src/main/om/core.cljs#L903
because `React.createClass` is not in React 16 anymore.

I didn't fix it because I was lazy.

We can either fix it in another PR or bring in `create-react-class` from CLJSJS solely for that namespace.

**Comment by anmonteiro** [comment]
Other than that I fixed the needed externs issues

**Comment by anmonteiro** [comment]
Also need to fix some server-side rendering stuff. We don't need to generate checksums or React IDs anymore

**Comment by dupuchba** [comment]
@anmonteiro can you plz explain why checksum/ids are not needed anymore ?
Plus, do you need help for this PR ?

**Comment by anmonteiro** [comment]
@dupuchba from https://reactjs.org/blog/2017/09/26/react-v16.0.html
> In addition, React 16 is better at hydrating server-rendered HTML once it reaches the client. It no longer requires the initial render to exactly match the result from the server. Instead, it will attempt to reuse as much of the existing DOM as possible. No more checksums!

**Comment by ItamarShDev** [comment]
Is there a plan to create a new version containing it?

**Comment by dark4eg** [comment]
@ItamarShDev 

> lein install

**Pull request merged**
