### PR TITLE
OM-637: `db->tree` naively resolves idents

### PR DESCRIPTION
**Pull request by anmonteiro**

### CODE REVIEW

**Comment by jasonjckn** [comment]
What about a unit test like this 
```
  (let [data {:todos/list [{:id 42 :states [:done :archived]} {:id 43 :states [:done :archived]}]}]
     (is (= (om/db->tree [{:todos/list [:id :states]}] data data)
            {:todos/list [{:id 42, :states [:done :archived]} {:id 43, :states [:done :archived]}]}))))
```

a query into denormalized data

**Comment by anmonteiro** [comment]
if those concern #604 then they should be provided in the PR that concerns that issue, no?

**Comment by jasonjckn** [comment]
IF you implemented "is an ident if the app state contains the key :table; otherwise it is simply a vector." this should fix both issues 604 and 637. So my thinking is why not add unit test for both issues.

**Comment by anmonteiro** [comment]
@jasonjckn this one needed to be solved first, but there's still a little bit of work that needs to be done to fully solve #604

**Pull request merged**
