### PR TITLE
Use react-create-class since React.createClass is deprecated

### LINKED ISSUE #881: Warning: A Component: React.createClass is deprecated
After upgrading om to version "1.0.0-beta1", the following error is printed in the console (in development mode only)
`react.inc.js:3287 Warning: A Component: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

### PR DESCRIPTION
**Pull request by wilkerlucio**
Closes #881

### CODE REVIEW

**Comment by dehli** [comment]
I did some investigating last night about this (thanks for the tips @wilkerlucio!) and I've started to come up with an alternative solution [here](https://github.com/omcljs/om/compare/master...dehli:fix/create-class). The advantage would be that we wouldn't have to pull in `create-react-class`. Note my fork doesn't address line 903 in `core.cljs`. I need to spend some more time going through the code base to figure that out.

However, as I was reading through the code I realized that `defui` is just a `React.Component` class so maybe we could use that here instead (with some refactoring)?

**Comment by swannodette** [comment]
Hrm shouldn't this PR bump the other React deps?

**Comment by wilkerlucio** [comment]
@swannodette React 16 is still in beta, you want that to be upgraded? I just used the createClass from 16 because that was the latest (and I don't think that matters much for this plugin). If you want I can upgrade React to beta, or downgrade the `react-create-class` to `15.5.3-0`, what you think?

**Comment by anmonteiro** [comment]
Closing

**Pull request closed without merging**
